# Generated by Django 5.2.13 on 2026-04-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=100)),
                ('hiragana', models.CharField(max_length=200)),
                ('katakana', models.CharField(blank=True, max_length=200, null=True)),
                ('meaning', models.TextField()),
                ('n_level', models.CharField(choices=[('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3'), ('N4', 'N4'), ('N5', 'N5')], default='N5', max_length=2)),
                ('memorize_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('LEARNING', 'Learning'), ('MASTERED', 'Mastered')], default='NOT_STARTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_vocabulary',
            },
        ),
    ]
