# Generated by Django 5.2.13 on 2026-06-02 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.TextField(blank=True, null=True)),
                ('korean_reading_detail', models.TextField(blank=True, null=True)),
                ('korean_reading', models.TextField(blank=True, null=True)),
                ('radical_desc_ko', models.TextField(blank=True, null=True)),
                ('etymology', models.TextField(blank=True, null=True)),
                ('stroke_count_ko', models.TextField(blank=True, null=True)),
                ('radical_ja', models.TextField(blank=True, null=True)),
                ('stroke_count_ja', models.TextField(blank=True, null=True)),
                ('onyomi', models.TextField(blank=True, null=True)),
                ('kunyomi', models.TextField(blank=True, null=True)),
                ('meaning_ja', models.TextField(blank=True, null=True)),
                ('level', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_kanji',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(blank=True, null=True)),
                ('korean_reading_detail', models.TextField(blank=True, null=True)),
                ('korean_reading', models.TextField(blank=True, null=True)),
                ('radical_desc_ko', models.TextField(blank=True, null=True)),
                ('etymology', models.TextField(blank=True, null=True)),
                ('stroke_count_ko', models.TextField(blank=True, null=True)),
                ('radical_ja', models.TextField(blank=True, null=True)),
                ('stroke_count_ja', models.TextField(blank=True, null=True)),
                ('onyomi', models.TextField(blank=True, null=True)),
                ('kunyomi', models.TextField(blank=True, null=True)),
                ('meaning_ja', models.TextField(blank=True, null=True)),
                ('level', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_vocabulary',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=255, unique=True)),
                ('meaning_ko', models.TextField(blank=True, null=True)),
                ('reading_hiragana', models.CharField(blank=True, max_length=200, null=True)),
                ('reading_katakana', models.CharField(blank=True, max_length=200, null=True)),
                ('result_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_word',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=255)),
                ('meaning_ko', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'tbl_search_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('hide_days', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(default='#3B82F6', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buttons', to='api.user')),
            ],
            options={
                'db_table': 'tbl_word_button',
            },
        ),
        migrations.CreateModel(
            name='WordStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('button', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_statuses', to='api.wordbutton')),
                ('vocabulary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='api.vocabulary')),
            ],
            options={
                'db_table': 'tbl_word_status',
            },
        ),
    ]
