# Generated by Django 5.2.13 on 2026-04-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_meaning_to_en_add_ko'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
                ('result_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_kanji_analysis',
            },
        ),
        migrations.RenameField(
            model_name='vocabulary',
            old_name='reading',
            new_name='reading_hiragana',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='reading_katakana',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
