# Generated by Django 5.2.13 on 2026-04-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_kanjianalysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=255, unique=True)),
                ('meaning_ko', models.TextField(blank=True, null=True)),
                ('reading_hiragana', models.CharField(blank=True, max_length=200, null=True)),
                ('reading_katakana', models.CharField(blank=True, max_length=200, null=True)),
                ('result_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_word',
            },
        ),
        migrations.DeleteModel(
            name='KanjiAnalysis',
        ),
        migrations.RenameField(
            model_name='vocabulary',
            old_name='reading_hiragana',
            new_name='reading',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='reading_katakana',
        ),
    ]
