# Generated by Django 5.2.13 on 2026-04-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_searchhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
