# Generated by Django 5.2.13 on 2026-05-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='hidden_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
