# Generated by Django 5.2.13 on 2026-05-26 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_vocabulary_hidden_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='hidden_until',
        ),
        migrations.CreateModel(
            name='VocabularyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vocabulary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='api.vocabulary')),
            ],
            options={
                'db_table': 'tbl_vocabulary_status',
            },
        ),
    ]
