# Generated by Django 5.2.13 on 2026-05-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_vocabulary_hidden_until_vocabularystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='hidden_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='VocabularyStatus',
        ),
    ]
