# Generated by Django 5.2.13 on 2026-05-28 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_vocabulary_hidden_until_delete_vocabularystatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_days', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buttons', to='api.user')),
            ],
            options={
                'db_table': 'tbl_word_button',
            },
        ),
        migrations.CreateModel(
            name='WordStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('button', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_statuses', to='api.wordbutton')),
                ('vocabulary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='api.vocabulary')),
            ],
            options={
                'db_table': 'tbl_word_status',
            },
        ),
    ]
