# Generated by Django 5.2.13 on 2026-05-29 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_wordbutton_wordstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordstatus',
            name='is_active',
        ),
    ]
