# Generated by Django 5.2.13 on 2026-05-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_wordstatus_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbutton',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wordbutton',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=20),
        ),
    ]
