# Generated by Django 5.2.13 on 2026-05-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_wordbutton_name_alter_wordbutton_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='hidden_until',
        ),
    ]
